In [1]:
import pandas as pd

In [2]:
runaways = pd.read_csv("/Users/arnavmathur/Desktop/PANDAS/Marvel.csv", index_col = 0)

In [3]:
runaways = pd.DataFrame({"gert": [1,2,3, 5], 
                         "geoffrey": [9, 18, 36, 72],
                         "karolina": [6, 12, 24, 42], 
                         "nico": [10, 9, 8, 7], 
                         "molly":[1, 10, 100, 1000], 
                         "alex": [23, 123, 911,13 ], 
                         "chase" :[2030, 17, 2017, 2003]},
                         index =["hulu", "fiction", "comic", "magic"])
runaways

         gert  geoffrey  karolina  nico  molly  alex  chase
hulu        1         9         6    10      1    23   2030
fiction     2        18        12     9     10   123     17
comic       3        36        24     8    100   911   2017
magic       5        72        42     7   1000    13   2003

In [8]:
runaways.filter(items = ["geoffrey", "alex"], axis = 1)

         geoffrey  alex
hulu            9    23
fiction        18   123
comic          36   911
magic          72    13

In [16]:
num = runaways[(runaways >= 10) & (runaways <= 30)].melt().dropna()

In [19]:
df = num.groupby("variable")
df

In [20]:
df.get_group("alex")

   variable  value
20     alex   23.0
23     alex   13.0

In [27]:
runaways.agg(["sum", "max", min, "var"])

,gert,geoffrey,karolina,nico,molly,alex,chase
sum,11.000000,135.00,84.0,34.000000,1111.00,1070.000000,6067.00
max,5.000000,72.00,42.0,10.000000,1000.00,911.000000,2030.00
min,1.000000,9.00,6.0,7.000000,1.00,13.000000,17.00
var,2.916667,776.25,252.0,1.666667,233840.25,186507.666667,999788.25

In [26]:
def Square(n):
    return n**2

def Cube(n):
    return n**3

In [29]:
runaways.agg(func = [Square, Cube])

          gert      geoffrey         karolina          nico          molly  \
        Square Cube   Square    Cube   Square   Cube Square  Cube   Square
hulu         1    1       81     729       36    216    100  1000        1
fiction      4    8      324    5832      144   1728     81   729      100
comic        9   27     1296   46656      576  13824     64   512    10000
magic       25  125     5184  373248     1764  74088     49   343  1000000

                       alex               chase
               Cube  Square       Cube   Square        Cube
hulu              1     529      12167  4120900  8365427000
fiction        1000   15129    1860867      289        4913
comic       1000000  829921  756058031  4068289  8205738913
magic    1000000000     169       2197  4012009  8036054027

In [32]:
runaways.agg({"chase": ["sum", "max"], "nico": ["min", "var"]}, axis = 0)

      chase      nico
max  2030.0       NaN
min     NaN  7.000000
sum  6067.0       NaN
var     NaN  1.666667

In [38]:
runaways.loc[["magic", "comic", "hulu"]].agg(["max", "min"])

     gert  geoffrey  karolina  nico  molly  alex  chase
max     5        72        42    10   1000   911   2030
min     1         9         6     7      1    13   2003