In [1]:
import pandas as pd, numpy as np

In [ ]:
# TASK 1

In [62]:
np.random.seed(1234)
year = pd.period_range(start = "1/1/2017", end = "12/31/2017", freq = "M", name = "Pandas!")
se = pd.Series(np.random.randint(1, 50, 12), year)
se

Pandas!
2017-01    48
2017-02    20
2017-03    39
2017-04    13
2017-05    25
2017-06    16
2017-07    24
2017-08    42
2017-09    27
2017-10    31
2017-11    44
2017-12    31
Freq: M, dtype: int64

In [ ]:
# TASK 2

In [17]:
np.random.seed(123)
rad = pd.DataFrame(abs(np.random.randn(5, 2)), columns = ["A", "B"], index = ["r1", "r2", "r3", "r4", "r5"])
(rad.T)*100

           r1          r2          r3          r4          r5
A  108.563060   28.297850   57.860025  242.667924  126.593626
B   99.734545  150.629471  165.143654   42.891263   86.674040

In [ ]:
# TASK 3

In [21]:
np.random.seed(14)
pd.DataFrame(np.random.randint(1, 100, 10).reshape(5, 2), columns = ["A", "B"])

    A   B
0  89  13
1  23  72
2  29  11
3  81  62
4  27  26

In [ ]:
# TASK 4

In [76]:
df = pd.read_csv("/Users/arnavmathur/Desktop/PANDAS/ABCD.csv", index_col = 0)
df.index = [f"r{i}" for i in range(10)]

df[["B", "C"]][4:7].sum(1)
df[["B", "C"]].loc[["r4", "r5", "r6"]].sum(1)
df.iloc[4:7, 1:3].sum(1)

r4    46
r5    50
r6    24
dtype: int64

In [ ]:
# TASK 5

In [77]:
df5 = pd.read_csv("/Users/arnavmathur/Desktop/PANDAS/BOOKS.csv", index_col = 0)
df5.pivot_table(index = "genre", aggfunc = {"price":[max, min], 
"rating":[max, min]}).groupby("genre").get_group("science")

          price        rating
            max    min    max  min
genre
science  205.99  12.99    5.0  1.2

In [ ]:
# TASK 6

In [90]:
df6 = pd.read_csv("/Users/arnavmathur/Desktop/PANDAS/STOCK.csv", index_col = 0)
df6

            AAPL  AMZN  MSFT month
2016-01-03   116   188    64   JAN
2016-01-10   135   210    50   JAN
2016-01-17    58   235    85   JAN
2016-01-24   145   119    89   JAN
2016-01-31   115   162   104   JAN
2016-02-07   102   228    83   FEB
2016-02-14   133   115    51   FEB
2016-02-21   146   185    59   FEB
2016-02-28    96   223    54   FEB
2016-03-06    84   144   133   MAR
2016-03-13   102   223    84   MAR
2016-03-20   110   224   121   MAR
2016-03-27   104   118    87   MAR
2016-04-03    53   119   131   APR
2016-04-10   144   128    60   APR
2016-04-17   102   121   111   APR
2016-04-24   107   208   130   APR
2016-05-01   125   158    52   MAY
2016-05-08   138   187    80   MAY
2016-05-15    89   167    94   MAY
2016-05-22    71   200   119   MAY
2016-05-29    91   173    84   MAY
2016-06-05   105   129   117   JUN
2016-06-12   133   194   111   JUN
2016-06-19   144   107    52   JUN
2016-06-26    63   190   106   JUN
2016-07-03   101   189   128   JUL
2016-07-10    60   169   116   JUL
2016-07-17    53   168    86   JUL
2016-07-24   118   144    52   JUL
2016-07-31   132   113    53   JUL
2016-08-07    64   131   148   AUG
2016-08-14   137   206   101   AUG
2016-08-21   144   109    61   AUG
2016-08-28   126   161    72   AUG
2016-09-04    80   143    91   SEP
2016-09-11    86   239   130   SEP
2016-09-18    54   174    67   SEP
2016-09-25    91   236   128   SEP
2016-10-02    95   239    92   OCT
2016-10-09   138   217    81   OCT
2016-10-16   126   180   114   OCT
2016-10-23    66   192    85   OCT
2016-10-30    57   125    76   OCT
2016-11-06   113   154   116   NOV
2016-11-13    51   146   115   NOV
2016-11-20   101   154    65   NOV
2016-11-27    62   108    88   NOV
2016-12-04    84   155   105   DEC
2016-12-11    51   134   102   DEC
2016-12-18   121   209   141   DEC
2016-12-25    63   236    90   DEC

In [ ]:
# TRY LATER

In [ ]:
# TASK 7

In [54]:
df1 = pd.read_csv("/Users/arnavmathur/Desktop/PANDAS/DF_1.csv", index_col = 0)
df1

   consoles  sales-in-Asia  sales-in-Europe
0       PS4            8.1             12.5
1     X-BOX            5.5              9.5
2  NINTENDO           11.7              7.2

In [55]:
df2 = pd.read_csv("/Users/arnavmathur/Desktop/PANDAS/DF_2.csv", index_col = 0)
df2

   consoles  sales-in-Africa  sales-in-Europe
0       PS4              3.2             12.5
1  NINTENDO              8.0              9.5
2     ATARI              9.4              7.2

In [58]:
pd.merge(df1, df2, on = "consoles", how = "outer", indicator = True)

,consoles,sales-in-Asia,sales-in-Europe_x,sales-in-Africa,sales-in-Europe_y,_merge
0,PS4,8.1,12.5,3.2,12.5,both
1,X-BOX,5.5,9.5,NaN,NaN,left_only
2,NINTENDO,11.7,7.2,8.0,9.5,both
3,ATARI,NaN,NaN,9.4,7.2,right_only

In [ ]:
# TASK 8

In [ ]:
# DO LATER