In [13]:
import pandas as pd
path = "/Users/arnavmathur/Desktop/DATA_1/"

In [14]:
states = pd.read_html("https://simple.wikipedia.org/wiki/List_of_U.S._states")

In [27]:
states
type(states)
len(states)
df_html = states[0]

In [40]:
df_html.to_csv(path + "HTML_DATA.csv", index = True, header = False)

In [41]:
usa = pd.read_csv(path + "HTML_DATA.csv", index_col = 0)

In [42]:
usa.loc[1]

Alabama              Alaska
AL                       AK
Montgomery           Juneau
Birmingham        Anchorage
Dec 14, 1819    Jan 3, 1959
4903185              731545
52420                665384
135767              1723337
50645                570641
131171              1477953
1775                  94743
4597                 245384
7                         1
Name: 1, dtype: object

In [44]:
df = pd.DataFrame({"a": [10, 20, 30], "b": [1, 2, 3]})
df

    a  b
0  10  1
1  20  2
2  30  3

In [45]:
df.to_csv(path + "CSV_DATA.csv", sep = ",", index = True)

In [46]:
df2 = pd.read_csv(path + "CSV_DATA.csv", index_col = 0)

In [48]:
df2

    a  b
0  10  1
1  20  2
2  30  3

In [51]:
df.to_excel(path + "EXCEL_DATA.xlsx", sheet_name = "Sheet1")

In [52]:
pd.read_excel(path + "EXCEL_DATA.xlsx")

   Unnamed: 0   a  b
0           0  10  1
1           1  20  2
2           2  30  3